# Generated by Django 5.2.7 on 2025-11-02 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "internal_id",
                    models.BigIntegerField(editable=False, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("STOCK_RESERVED", "Stock Reserved"),
                            ("STOCK_FAILED", "Stock Failed"),
                            ("PAID", "Paid"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CREATED",
                        max_length=32,
                    ),
                ),
                ("total_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("transaction_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-internal_id"],
            },
        ),
    ]
