"""
Django settings for gateway project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from pythonjsonlogger import jsonlogger
from urllib.parse import urlparse


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APPS_DIR = BASE_DIR / "apps"
if str(APPS_DIR) not in sys.path:
    sys.path.insert(0, str(APPS_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-replace-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

DOMAIN_APPS = [
    "orders",
    "monitoring",
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'django_redis',
    'corsheaders',
]

INSTALLED_APPS += DOMAIN_APPS
INSTALLED_APPS += THIRD_PARTY_APPS

PROJECT_MIDDLEWARE = [
    'gateway.middleware.RequestIdMiddleware',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "gateway.middleware.ApiSizeLimitMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE += PROJECT_MIDDLEWARE

ROOT_URLCONF = 'gateway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gateway.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "orders"),
        "USER": os.environ.get("POSTGRES_USER", "app"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "app"),
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INVENTORY_BASE_URL = os.environ.get("INVENTORY_BASE_URL", "http://inventory:9001")
PAYMENTS_BASE_URL  = os.environ.get("PAYMENTS_BASE_URL",  "http://payments:9002")
HTTP_TIMEOUT_SECS  = float(os.environ.get("HTTP_TIMEOUT_SECS", "5"))

# adapters
USE_HTTP_ADAPTERS = os.environ.get("USE_HTTP_ADAPTERS", "1") in {"1", "true", "True"}


# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {"()": "gateway.logging_filters.RequestIdFilter"},
    },
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "fmt": "%(asctime)s %(levelname)s %(name)s %(message)s %(request_id)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_id"],
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "apps":   {"handlers": ["console"], "level": "INFO", "propagate": False},
        "uvicorn.error": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
}

# HTTP CONTROL
HTTP_CIRCUIT_FAIL_THRESHOLD = int(os.environ.get("HTTP_CIRCUIT_FAIL_THRESHOLD", 5))
HTTP_CIRCUIT_RESET_TIMEOUT = float(os.environ.get("HTTP_CIRCUIT_RESET_TIMEOUT", 30.0))  # segundos
HTTP_TIMEOUT_SECS = float(os.environ.get("HTTP_TIMEOUT_SECS", 3.0))
HTTP_RETRY_MAX = int(os.environ.get("HTTP_RETRY_MAX", 3))
HTTP_RETRY_BACKOFF_BASE = float(os.environ.get("HTTP_RETRY_BACKOFF_BASE", 0.15))
HTTP_RETRY_MAX_SLEEP = float(os.environ.get("HTTP_RETRY_MAX_SLEEP", 0.5))

if "pytest" in sys.modules:
    HTTP_RETRY_MAX = 2
    HTTP_RETRY_BACKOFF_BASE = 0.01
    HTTP_RETRY_MAX_SLEEP = 0.02

# THROTTLING
REST_FRAMEWORK = {
    # …
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # globales
        "anon": "100/min",    # tráfico anónimo total
        "user": "600/min",    # si algún día autenticamos
        # scopes
        "orders_create": "10/min",   # POST /api/orders/ (crear)
        "orders_list": "120/min",    # GET /api/orders/
        "orders_detail": "300/min",  # GET /api/orders/<id>/
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/1"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "ordersvc",
    }
}
# (opcional) usar un alias específico para throttling
THROTTLE_DEFAULT_CACHE = "default"

# CORS
# Origins permitidos (coma-separados). Ej: "https://mi-frontend.com,https://admin.mi-frontend.com"
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = False  # si no usas cookies/sesión desde front
CORS_ALLOW_HEADERS = list({
    "accept", "accept-encoding", "authorization", "content-type",
    "origin", "x-csrftoken", "x-requested-with",
    "idempotency-key", "request-id"   # <- cabeceras propias
})
# Opcional: limitar a rutas API
CORS_URLS_REGEX = r"^/api/.*$"

# security
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))  # p.ej. 31536000 en prod
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Redirect a HTTPS (solo si hay TLS delante)
SECURE_SSL_REDIRECT = bool(int(os.getenv("SECURE_SSL_REDIRECT", "0")))

# Cookies seguras
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Otras cabeceras de seguridad
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

# COOP ya lo estabas enviando desde Django (si no, añade):
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"


# content-security-policy (CSP)
CSP_DEFAULT_SRC = ("'none'",)
CSP_FRAME_ANCESTORS = ("'none'",)
CSP_CONNECT_SRC = ("'self'",)   # si la API es consumida por front, añade su dominio
# Si sirves estáticos desde el mismo dominio:
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", "data:")

# limit request size
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(1 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(1 * 1024 * 1024)))